root = "."
tmp_dir = "dist"
build_args = []
exclude_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
enable_color = true
log_color_main = "\033[32m"
log_color_app = "\033[34m"
log_color_watcher = "\033[36m"